- name: Creacion directorio
  file:
   path: /home/ubuntu/tomcat
   state: directory
   mode: 0755
   owner: ubuntu
   group: ubuntu

- name: Descarga de Tomcat
  get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu/tomcat

- name: Extraccion del archivo
  unarchive: src=/home/ubuntu/tomcat/apache-tomcat-8.0.27.tar.gz dest=/home/ubuntu/tomcat
